#!/bin/sh
# force rebuild

case "$1" in
    -h)
	echo "Force rebuild Docker image and Vagrant box"
	exit 0
      ;;
esac
 
# rebuild Vagrant box 
echo "rebuild OpenDDS Vagrant box..."
git clone https://github.com/larry-fuy/vagrant-opendds
cd vagrant-opendds && build.sh
cd ..

# rebuild Docker image
echo "rebuild OpenDDS Docker image..."
git clone https://github.com/larry-fuy/docker-opendds
cd docker-opendds && build.sh
cd ..

exit