#!/bin/sh
# force rebuild

rebuild_v=0
rebuild_d=0
OPTIONS=$(getopt -o h -- "$@")
eval set -- "$OPTIONS"

while [ $# -gt 0 ]
do
    case "$1" in
     	  -h)
	        echo "Usage: rebuild [OPTIONS] [vagrant | docker]"
		echo "Force rebuild Docker image and Vagrant box";
		echo "Options: ";
		echo "    -h   Show this message"
		break ;;
    	vagrant)
		rebuild_v=1; shift ;;
    	docker)
		rebuild_d=1; shift ;;
	--) shift ;;
	*) echo "Internal error!" ; exit 1 ;;
    esac
done
 
# rebuild Vagrant box 
if [ $rebuild_v -eq 1 ]; then
   echo "rebuild OpenDDS Vagrant box..."
   if [ -d vagrant-opendds ] ; then
      rm -rf vagrant-opendds
   fi
   git clone https://github.com/larry-fuy/vagrant-opendds
   cd vagrant-opendds && ./build.sh
cd ..
fi

# rebuild Docker image
if [ $rebuild_d -eq 1 ]; then
   echo "rebuild OpenDDS Docker image..."
   if [ -d docker-opendds ] ; then
      rm -rf docker-opendds
   fi
   git clone https://github.com/larry-fuy/docker-opendds
   cd docker-opendds && ./build.sh
cd ..
fi
